nameA: wild
nameB: dom
size_popA: 20
size_popB: 20
timeStamp: /scratch/eburban/DomIsol/test_RIDGE
nLoci: 1000
Nref: 85000
mu: 3e-8
rho_over_theta: 5
locus_length: 10000
RIDGE_template: /home/genouest/cnrs_umr6553/eburban/RIDGE/template/RIDGE_template.yaml
n_sim_iteration: 10
param_file: /home/genouest/cnrs_umr6553/eburban/RIDGE/config/param_space_faker.txt
container_path: /home/genouest/cnrs_umr6553/eburban/RIDGE/container/
